### PR TITLE
EL7 + Flag Options + URL

### PR DESCRIPTION
**Pull request by clwells**
I added in a few things that we needed including:

- EL7 support
- Flag options
- URL argument support.

Thanks!

Chris

### CODE REVIEW

**Comment by bastiaanvanassche** [comment]
Hi Chris

First of all: thanks for the pull request.

I'm afraid I cannot accept it right now because the role is now failing on Ubuntu 12.04 and 16.04 (14.04 is still ok)

I've been adding some tests + travis configuration to generate some proof. Everything is on the branch 'nexcess-master'

These are the test results
https://travis-ci.org/bastiaanvanassche/ansible-role-s3fs-fuse/builds/203242212

Would you mind having a look at it?

Thanks

Bastiaan

**Comment by clwells** [comment]
Bastiaan - The 16.04 and 12.04 may just be missing repos that are needed for these basic packages.  I spun up a 16.04 vanilla Ubuntu instance and 'automake' was available from the provided repos.

Chris

**Comment by bastiaanvanassche** [comment]
Hi Chris

After merging your pull request, I've been re-adding the param _update_cache=yes_ on the task 'install dependent packages for s3fs-fuse'. Tests on 16.04, 14.04 and 12.04 are all green now.

Greetings

Bastiaan

**Comment by clwells** [comment]
Great :)

**Pull request merged**
